version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: python manage.py test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "your-fingerprint-here"  # Replace with your actual SSH key fingerprint
      - run:
          name: Deploy to Server
          command: |
            ssh user@your-server-ip << 'EOF'
              git pull origin main  # Pull the latest changes
              python manage.py migrate  # Run migrations
              python manage.py collectstatic --noinput  # Collect static files (if using Django)
              sudo systemctl restart your-app.service  # Replace with your actual app service name (if applicable)
              exit
            EOF

workflows:
  build-and-test:
    jobs:
      - test-python
      - deploy:
          requires:
            - test-python